---
title: "Life Expectancy"
author: "Taalin"
date: "10/26/2020"
output: html_document
---

```{r setup-packages, message = FALSE, warning = FALSE}
library(tidyverse)
library(plyr) #package for join command
library(broom)
```

```{r}
report_2020 <- read_csv("data/2020.csv")
report_2018 <- read_csv("data/2018.csv") %>% 
  mutate(year = "2018") %>% 
  mutate(`Perceptions of corruption` = as.numeric(`Perceptions of corruption`))
report_2019 <- read_csv("data/2019.csv") %>% 
  mutate(year = "2019")

worldhappiness <- full_join(report_2018, report_2019)

view(worldhappiness)
```

```{r}
life_expectancy <- worldhappiness %>% 
  filter(! is.na(`Healthy life expectancy`)) %>% 
  select(`Country or region`, Score, `Healthy life expectancy`, year)

year2019 <- life_expectancy %>% 
  filter(year == "2019")
year2018 <- life_expectancy %>% 
  filter(year == "2018")

view(life_expectancy)
view(year2019)
```

### Correlation
```{r}
life_expectancy %>% 
  summarize(r_overall = cor(Score, `Healthy life expectancy`))

year2019 %>% 
  summarize(r_2019 = cor(Score, `Healthy life expectancy`))

year2018 %>% 
  summarize(r_2018 = cor(Score, `Healthy life expectancy`))
```

### Linear Model & Visualization

```{r}
m_life <- lm(Score ~ `Healthy life expectancy`, data = worldhappiness)

m_life %>%
  tidy() %>%
  select(term, estimate) 

ggplot(data = life_expectancy, aes(x = `Healthy life expectancy`,
                              y = Score)) + 
  geom_point(size = 0.8) + 
  geom_smooth(method = lm, color = "blue", size = 0.5) +
  theme_bw() +
  labs(title = "Linear model for relationship between healthy life expectancy
and overall happiness score",
       subtitle = "Strong, positive correlation",
       x = "Healthy Life Expectancy Score",
       y = "Overall Happiness Score")

```
### T-test 

```{r}
worldhappiness <- worldhappiness %>%
  mutate(happyrating = case_when(Score <= 4.5 ~ "unhappy",
                                 Score > 4.5 & Score <= 6 ~ "moderately happy", 
                                 Score > 6 ~ "happy")) %>%
  mutate(life_rating = case_when(`Healthy life expectancy` <= 0.5 ~ "poor",
                                 `Healthy life expectancy` > 0.5 & 
                                   `Healthy life expectancy` <= 0.8 ~ "moderate",
                               `Healthy life expectancy` > 0.8 ~ "good"))

```



