---
title: "Results"
author: "Anna MacFarlane, Edgar Salas, Jerry Fu, Taalin RaoShah"
date: "10/27/2020"
output: html_document
---

```{r setup-packages, message = FALSE, warning = FALSE}
library(tidyverse)
library(plyr) #package for join command
library(maps) #package for world map
```

```{r load-datasets, message = FALSE, warning = FALSE}
report_2018 <- read_csv("data/2018.csv") %>% 
  mutate(year = "2018",
         `Perceptions of corruption` = as.numeric(`Perceptions of corruption`))
report_2019 <- read_csv("data/2019.csv") %>% 
  mutate(year = "2019")
country_region <- read_csv("data/2020.csv") %>% 
  mutate(year = "2020") %>% 
  select(`Country name`, `Regional indicator`)

names(country_region) <- c("Country", "Region")
names(report_2018) <- str_replace_all(names(report_2018), c(" " = "_"))
names(report_2019) <- str_replace_all(names(report_2018), c(" " = "_"))

worldhappiness <- full_join(report_2018, report_2019) 
worldhappiness <- worldhappiness %>% 
  rename(c("Country_or_region" = "Country")) %>% 
  left_join(country_region)

glimpse(worldhappiness)
```

```{r add-region}
worldhappiness %>% 
  filter(is.na(Region))

worldhappiness <- worldhappiness %>% 
  mutate(Region = ifelse(Country == "Taiwan", "East Asia", Region)) %>%
  mutate(Region = ifelse(Country == "Qatar", "Middle East and North Africa", Region)) %>% 
  mutate(Region = ifelse(Country == "Trinidad & Tobago", "Latin America and Caribbean", Region)) %>% 
  mutate(Region = ifelse(Country == "Belize", "Latin America and Caribbean", Region)) %>% 
  mutate(Region = ifelse(Country == "Northern Cyprus", "Middle East and North Africa", Region)) %>% 
  mutate(Region = ifelse(Country == "Hong Kong", "East Asia", Region)) %>% 
  mutate(Region = ifelse(Country == "Bhutan", "South Asia", Region)) %>% 
  mutate(Region = ifelse(Country == "Somalia", "Middle East and North Africa", Region)) %>% 
  mutate(Region = ifelse(Country == "Sudan", "Middle East and North Africa", Region)) %>% 
  mutate(Region = ifelse(Country == "Angola", "Middle East and North Africa", Region)) %>% 
  mutate(Region = ifelse(Country == "Syria", "Middle East and North Africa", Region)) %>% 
  mutate(Region = ifelse(Country == "North Macedonia", "Central and Eastern Europe", Region))
```

### Is there a relationship between region of the world and happiness score?
```{r world-map, fig.width = 10, fig.height = 5}
world_map <- map_data("world") %>% 
  mutate(region = ifelse(region == "USA", "United States", region)) %>% 
  mutate(region = ifelse(region == "Democratic Republic of the Congo", "Congo (Kinshasa)", region))
  
happiness_score_map <- left_join(worldhappiness, world_map, by = c("Country" = "region"))
ggplot(happiness_score_map, aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = Score), color = "white") +
  scale_fill_viridis_c(option = "D")
```
https://www.datanovia.com/en/blog/how-to-create-a-map-using-ggplot2/

```{r chi-sq-region-score, warning = FALSE}
chisq.test(worldhappiness$Score, worldhappiness$Region, simulate.p.value = TRUE)
```

